//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ATTENDEES_APPOINTMENT
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdAppointment { get; set; }
        public bool Accepted { get; set; }
        public bool HasReminder { get; set; }
        public string Note { get; set; }
    }
}
