//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AppointmentBookEntities : DbContext
    {
        public AppointmentBookEntities()
            : base("name=AppointmentBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<APPOINTMENT> APPOINTMENTs { get; set; }
        public virtual DbSet<ATTENDEES_APPOINTMENT> ATTENDEES_APPOINTMENT { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
        public virtual DbSet<REMINDER> REMINDERs { get; set; }
        public virtual DbSet<ROLE> ROLEs { get; set; }
        public virtual DbSet<USER> USERS { get; set; }
    
        public virtual ObjectResult<GetAppointmentData_Result> GetAppointmentData()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAppointmentData_Result>("GetAppointmentData");
        }
    }
}
